#Forced rebuild: 1

packages:
  branch_codenames:
    master: trusty-unstable
    production: trusty-stable

jobs:
  composed-utils:
    builder: "make"
    base: "quay.io/madebymany/build-bases:trusty"
    packages:
      - type: debian
        name: composed-utils
        depends:
          - augeas-tools
          - jq
          - sed
          - slackcat
        repos:
          - composed-public
        target: install