#!/bin/bash
set -e

url=$REDIS_URL
eval "$(echo "$url" | \
  sed -ne 's/^redis:\/\/\([-\.[:alnum:]]\{1,\}\)\(:\([[:digit:]]\{1,\}\)\)\{0,1\}\(\/\([[:digit:]]\{1,\}\)\)\{0,1\}/url_matched=1 redis_host=\1 redis_port=\3 redis_db=\5/p')"


if [ -z "$url_matched" ]; then
  echo "$0: '$url' is not a valid Redis URL" >&2
  exit 1
fi

[ -z "$redis_host" ] && redis_host=localhost
[ -z "$redis_port" ] && redis_port=6379
[ -z "$redis_db" ] && redis_db=0

exec redis-cli -h "${redis_host}" -p "${redis_port}" -n "${redis_db}" "$@"
